### ISSUE TITLE
[CHANNEL-REQUEST]

### ISSUE THREAD

**Issue by NickelSickle** [WeebDataHoarder/ln.lightninghoarder.net#1]
## Your Node
https://1ml.com/node/0327bfdbef7c13f813b46ee23d9fbd3de1202bbcbb51f07a69cf9378e2421231a5

Just a fun side project for a fellow crypto enthusiast. Trying to build the network, particularly the Reddit Megahub. Ideally I'd like to turn this channel request into a 1M triangle.

### Feature List
Mark any that you have setup and enabled. These are not required items, just check the ones that apply.

* [ ] [Anchor outputs / anchor commitments](https://bitcoinops.org/en/topics/anchor-outputs/)
* [ ] [WUMBO channels](https://bitcoinops.org/en/topics/large-channels/)
* [ ] Automatic channel balancing
* [ ] Automatic fee scaling
* [ ] Low channel commitment reserve
* [ ] Battery-backed
* [ ] Redundant internet uplink
* [x] 24/7 operation

---

### ⚠️ Safety Checklist ⚠️
These items here are for your own safety and not require recovery assistance in case the worst happens to any node.

* [x] Regularly check and upgrade node software for new features / patches
* [x] Backed up (or written down) own node seed / entropy: _BIP39_, _[aezeed (lnd)](https://github.com/lightningnetwork/lnd/blob/master/docs/safety.md#aezeed)_, _[hsm_secret (c-lightning)](https://github.com/ElementsProject/lightning/blob/master/doc/BACKUP.md#hsm_secret)_
* [x] Configured `Static Channel Backups (SCB, channel.backup)` / `Static Remote Key` and they are automatically stored elsewhere: _[SCBs (lnd)](https://github.com/lightningnetwork/lnd/blob/master/docs/safety.md#static-channel-backups-scbs)_, _[file-based backups (c-lightning)](https://github.com/ElementsProject/lightning/blob/master/doc/BACKUP.md)_
* [ ] _(Optional)_ Configured a Watchtower Client: _[Altruist Watchtower (lnd)](https://github.com/lightningnetwork/lnd/blob/master/docs/watchtower.md)_, _[BOLT13 / teos (c-lightning)](https://github.com/talaia-labs/python-teos/tree/master/watchtower-plugin)_

---

### Liquidity Details
* **Amount in satoshi**: 1,000,000
* **Expected duration**: Indefinite? Idk!
* **Public channel**: Yes

### Additional notes
Me love you long time

**Comment by WeebDataHoarder** [comment]
I see you have this pending triangle on reddit open. I can take B there https://www.reddit.com/r/TheLightningNetwork/comments/n7s4px/lightning_network_triangle_megathread_build_the/gzh7n7u/

**Comment by NickelSickle** [comment]
Good morning, I just woke up and went to the thread, I already had comments
for nodes B and C. I'll make another triangle in the same thread and add
you as B.

**Comment by WeebDataHoarder** [comment]
I'll close this issue then, seems like we have a triangle
